### ISSUE TITLE
training over new dataset

### ISSUE THREAD

**Issue by goelankur7** [karpathy/neuraltalk#25]
I am training it over new dataset. I am getting this error in save checkpoint
36/1850 batch done in 2.356s. at epoch 0.97. loss cost = 9.295156, reg cost = 0.000000, ppl2 = 4.59 (smooth 14.32)
evaluating val performance in batches of 100
Traceback (most recent call last):
  File "driver.py", line 315, in <module>
    main(params)
  File "driver.py", line 232, in main
    val_ppl2 = eval_split('val', dp, model, params, misc) # perform the evaluation on VAL set
  File "/root/neuraltalk/imagernn/imagernn_utils.py", line 38, in eval_split
    ppl2 = 2 ** (logppl / logppln) 
ZeroDivisionError: integer division or modulo by zero

**Comment by lebronze** [comment]
Well, i had the same problem. You can make the para 'logppl' and 'logppln' to a very little value, such as 0.0001 in the line 72,73 driver.py.
That works for me.

**Comment by lebronze** [comment]
Dear @goelankur7 , did you finally train your multimodal RNN model successfully? And could you test you own images on your multimodal RNN model?

**Comment by infinity0a** [comment]
hey @lebronze, I had this problem as well, and I use the "0.0001". It still doesn't work. Do you have any other fixes?

**Comment by nyj-ocean** [comment]
@agoel-cs @lebronze @infinity0a 
how did you create the `json` file of your own dataset like `dataset_coco.json` file?
